apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vaccine-traceability-hapi
  name: vaccine-traceability-hapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaccine-traceability-hapi
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: vaccine-traceability-hapi
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - image: eoscostarica506/vaccine-traceability-hapi
          imagePullPolicy: 'Always'
          name: 'vaccine-traceability-hapi'
          envFrom:
            - configMapRef:
                name: vaccine-traceability-hapi-config
          ports:
            - containerPort: 9090
          volumeMounts:
            - mountPath: /usr/app
              name: hapi
              subPathExpr: $(CODE_DIRECTORY)
      restartPolicy: Always
      volumes:
        - name: hapi
          nfs:
            server: nfs-server-new
            path: /home/ubuntu/
