apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hapi
  name: hapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hapi
  template:
    metadata:
      labels:
        app: hapi
    spec:
      imagePullSecrets:
        - name: github-docker
      containers:
        - image: ${DOCKER_REGISTRY}/${IMAGE_NAME_HAPI}:${VERSION}
          name: hapi
          ports:
            - containerPort: 3005
          resources:
            requests:
              cpu: 200m
            limits:
              cpu: "1"
          envFrom:
            - secretRef:
                name: hapi-secrets
