apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hasura
  name: hasura
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hasura
  template:
    metadata:
      labels:
        app: hasura
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - image: ${DOCKER_REGISTRY}/${IMAGE_NAME}:${VERSION}
          name: hasura
          ports:
            - containerPort: 8080
              name: http
          resources:
            requests:
              cpu: 150m
            limits:
              cpu: "1"
          envFrom:
            - secretRef:
                name: hasura-secret
