apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vaccine-traceability-hasura
  name: vaccine-traceability-hasura
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaccine-traceability-hasura
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: vaccine-traceability-hasura
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - args:
            - graphql-engine
            - serve
            - --enable-console
          env:
            - name: HASURA_GRAPHQL_ADMIN_SECRET
              valueFrom:
                secretKeyRef:
                  name: dashboard-secret
                  key: HASURA_GRAPHQL_ADMIN_SECRET
            - name: HASURA_GRAPHQL_UNAUTHORIZED_ROLE
              valueFrom:
                secretKeyRef:
                  name: dashboard-secret
                  key: HASURA_GRAPHQL_UNAUTHORIZED_ROLE
          envFrom:
            - configMapRef:
                name: vaccine-traceability-hasura-config
          image: hasura/graphql-engine:v1.2.1.cli-migrations-v2
          imagePullPolicy: 'IfNotPresent'
          name: 'vaccine-traceability-hasura'
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /hasura-migrations
              name: vaccine-traceability-hasura1
              subPathExpr: $(MIGRATION_DIRECTORY)
            - mountPath: /hasura-metadata
              name: vaccine-traceability-hasura2
              subPathExpr: $(METADATA_DIRECTORY)
      restartPolicy: Always
      volumes:
        - name: vaccine-traceability-hasura1
          nfs:
            server: nfs-server-new
            path: /home/ubuntu
        - name: vaccine-traceability-hasura2
          nfs:
            server: nfs-server-new
            path: /home/ubuntu
