apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: inmutrust
  labels:
    version: "1"
parameters:
  fromBackup: ""
  numberOfReplicas: "1"
  staleReplicaTimeout: "2880"
provisioner: driver.longhorn.io
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
