apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: postgres
    version: ${VERSION}
  name: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      version: ${VERSION}
  template:
    metadata:
      labels:
        app: postgres
        version: ${VERSION}
    spec:
      imagePullSecrets:
        - name: github-docker
      containers:
        - image: postgres:11.5-alpine
          imagePullPolicy: "Always"
          name: postgres
          envFrom:
            - configMapRef:
                name: postgres-secrets
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres
  volumeClaimTemplates:
    - metadata:
        name: postgres
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: inmutrust
        resources:
          requests:
            storage: 100Gi
