apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - name: api
      port: 5672
      targetPort: 5672
      protocol: TCP
    - name: admin
      port: 15672
      targetPort: 15672
      protocol: TCP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-secrets
  labels:
    version: ${VERSION}
data:
  RABBITMQ_ADMIN_USER: ${RABBITMQ_ADMIN_USER}
  RABBITMQ_ADMIN_PASSWORD: ${RABBITMQ_ADMIN_PASSWORD}
  RABBITMQ_ENABLED_PLUGINS_FILE: ${RABBITMQ_ENABLED_PLUGINS_FILE}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - image: rabbitmq:3-management-alpine
          name: rabbitmq
          ports:
            - containerPort: 5672
              name: api
            - containerPort: 15672
              name: admin
          volumeMounts:
            - name: rabbitmq-plugins
              mountPath: /rabbitmq
          resources:
            requests:
              cpu: 200m
            limits:
              cpu: "1"
          envFrom:
            - configMapRef:
                name: rabbitmq-secrets
      volumes:
        - name: rabbitmq-plugins
          configMap:
            name: rabbitmq-plugins
            defaultMode: 0777
