---
kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: github-docker
stringData:
  .dockerconfigjson: '{"auths":{"docker.pkg.github.com":{"auth": "eGF2aWVyNTA2OmZmYTFkYjAyOWMxNDA3MGYxMTllNDA3MjYxNjBlODE3NmE0NDIyNzQ"}}}'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secrets
  labels:
    version: ${VERSION}
data:
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_DB: ${POSTGRES_DB}
  POSTGRES_DATA: ${POSTGRES_DATA}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hasura-secrets
  labels:
    version: ${VERSION}
data:
  HASURA_GRAPHQL_ENABLE_CONSOLE: ${HASURA_GRAPHQL_ENABLE_CONSOLE}
  HASURA_GRAPHQL_DATABASE_URL: ${HASURA_GRAPHQL_DATABASE_URL}
  HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
  HASURA_GRAPHQL_UNAUTHORIZED_ROLE: ${HASURA_GRAPHQL_UNAUTHORIZED_ROLE}
  HASURA_GRAPHQL_JWT_SECRET: ${HASURA_GRAPHQL_JWT_SECRET}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wallet-secrets
  labels:
    version: ${VERSION}
data:
  WALLET_DATA: ${WALLET_DATA}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hapi-secrets
  labels:
    version: ${VERSION}
data:
  HAPI_SERVER_PORT: ${HAPI_SERVER_PORT}
  HAPI_SERVER_ADDRESS: ${HAPI_SERVER_ADDRESS}
  HAPI_EOS_API_ENDPOINT: ${HAPI_EOS_API_ENDPOINT}
  HAPI_EOS_API_CHAIN_ID: ${HAPI_EOS_API_CHAIN_ID}
  HAPI_EOS_BASE_ACCOUNT: ${HAPI_EOS_BASE_ACCOUNT}
  HAPI_EOS_BASE_ACCOUNT_PASSWORD: ${HAPI_EOS_BASE_ACCOUNT_PASSWORD}
  HAPI_EOS_WALLET_URL: ${HAPI_EOS_WALLET_URL}
  HAPI_HASURA_URL: ${HAPI_HASURA_URL}
  HAPI_HASURA_ADMIN_SECRET: ${HAPI_HASURA_ADMIN_SECRET}
  HAPI_JWT_SECRET: ${HAPI_JWT_SECRET}
  HAPI_JWT_ISS: ${HAPI_JWT_ISS}
  HAPI_JWT_ALGORITHM: ${HAPI_JWT_ALGORITHM}
  HAPI_SIMPLEASSETS_ACCOUNT: ${HAPI_SIMPLEASSETS_ACCOUNT}
