name: Build images from latest `main` branch

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1

      - name: Setup Docker
        uses: docker-practice/actions-setup-docker@0.0.1

      - name: Log in to docker registry
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build new images and push
        run: |
          make \
            build-all \
            push-images
        env:
          # Webapp
          FAST_REFRESH: "false"
          PORT: "3000"
          REACT_APP_VERSION: "1.0.0"
          REACT_APP_NAME: "inmutrust"
          REACT_APP_TITLE: "Vaccine Traceability POC"
          REACT_APP_LOGO: "https://raw.githubusercontent.com/eoscostarica/design-assets/master/logos/eosCR/fullColor-vertiall-transparent-white.png"
          REACT_APP_FOOTER_LINKS: "[]"
          REACT_APP_UAL_APP_NAME: "VaccineTraceability"
          REACT_APP_UAL_API_PROTOCOL: "https"
          REACT_APP_UAL_API_HOST: "jungle.eosio.cr"
          REACT_APP_UAL_API_PORT: "443"
          REACT_APP_UAL_CHAIN_ID: "2a02a0053e5a8cf73a56ba0fda11e4d92e0238a4a2aa74fccf46d5a910746840"
          REACT_APP_HASURA_URL: "https://graphql.inmutrust.com/v1/graphql"

      - name: Build and deploy kubernetes files
        id: build_kubernetes_files
        run: |
          make \
            build-kubernetes \
            deploy-kubernetes
        env:
          # general
          NAMESPACE: inmutrust
          INGRESS_HOST: inmutrust.com
          INGRESS_GRAPHQL_HOST: graphql.inmutrust.com
          # postgres
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_DATA: ${{ secrets.POSTGRES_DATA }}
          DATABASE_DIRECTORY: ${{ secrets.DATABASE_DIRECTORY }}
          # hapi
          HAPI_EOS_API_ENDPOINT: ${{ secrets.HAPI_EOS_API_ENDPOINT }}
          HAPI_EOS_API_CHAIN_ID: ${{ secrets.HAPI_EOS_API_CHAIN_ID }}
          HAPI_EOS_BASE_ACCOUNT: ${{ secrets.HAPI_EOS_BASE_ACCOUNT }}
          HAPI_EOS_BASE_ACCOUNT_PASSWORD: ${{ secrets.HAPI_EOS_BASE_ACCOUNT_PASSWORD }}
          HAPI_EOS_MECHANICS_ACCOUNT: ${{ secrets.HAPI_EOS_MECHANICS_ACCOUNT }}
          HAPI_EOS_MECHANICS_PASSWORD: ${{ secrets.HAPI_EOS_MECHANICS_PASSWORD }}
          HAPI_EOS_WALLET_URL: ${{ secrets.HAPI_EOS_WALLET_URL }}
          HAPI_HASURA_URL: ${{ secrets.HAPI_HASURA_URL }}
          HAPI_HASURA_ADMIN_SECRET: ${{ secrets.HAPI_HASURA_ADMIN_SECRET }}
          HAPI_JWT_SECRET: ${{ secrets.HAPI_JWT_SECRET }}
          HAPI_JWT_ISS: ${{ secrets.HAPI_JWT_ISS }}
          HAPI_JWT_ALGORITHM: ${{ secrets.HAPI_JWT_ALGORITHM }}
          HAPI_SERVER_PORT: ${{ secrets.HAPI_SERVER_PORT }}
          HAPI_SERVER_ADDRESS: ${{ secrets.HAPI_SERVER_ADDRESS }}
          HAPI_SIMPLEASSETS_ACCOUNT: ${{ secrets.HAPI_HASURA_ADMIN_SECRET }}
          # wallet
          WALLET_DATA: ${{ secrets.WALLET_DATA }}
          # hasura
          HASURA_GRAPHQL_ENABLE_CONSOLE: ${{ secrets.HASURA_GRAPHQL_ENABLE_CONSOLE }}
          HASURA_GRAPHQL_DATABASE_URL: ${{ secrets.HASURA_GRAPHQL_DATABASE_URL }}
          HASURA_GRAPHQL_ADMIN_SECRET: ${{ secrets.HASURA_GRAPHQL_ADMIN_SECRET }}
          HASURA_GRAPHQL_UNAUTHORIZED_ROLE: ${{ secrets.HASURA_GRAPHQL_UNAUTHORIZED_ROLE }}
          HASURA_GRAPHQL_JWT_SECRET: ${{ secrets.HASURA_GRAPHQL_JWT_SECRET }}
